language: swift
osx_image: xcode10

matrix:
  include:
  - os: osx
    env: BUILD_ENV=arm64 BUILD_TYPE=Release SDK=iphoneos12.0

  - os: osx
    env: BUILD_ENV=x64 BUILD_TYPE=Release SDK=iphonesimulator12.0

install:
  #- brew install appledoc
  - .script/download_libs.sh ${BUILD_ENV}

script:
  # - xcodebuild -showsdks
  - xcodebuild -list -project ElastosCarrierSDK.xcodeproj
  # default build release
  - xcodebuild -scheme ElastosCarrierSDK build -sdk ${SDK}
  #- ./docs.sh
